name: Run Data prep

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  release:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          cache-env: true
          environment-file: environment.yml

      - name: run
        run: |
          wget http://cf.10xgenomics.com/samples/cell-exp/1.1.0/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz
          tar -xzf pbmc3k_filtered_gene_bc_matrices.tar.gz
          pytest test.py

